language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.4.0.RELEASE/spring-boot-cli-1.4.0.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.4.0.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.4.0.RELEASE/bin
- spring --version
- wget -O cf-linux-amd64.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.11.2&source=github-rel"
- tar xvfz cf-linux-amd64.tgz
- chmod 755 ./cf
script:
- ./build
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ]; then
  ./deploy ; fi
notifications:
  slack:
    secure: HStV2wAWvnkayC7Zv5QAAS+rlxH3C0KVqQO4TeurFsLGFOM6laDZRhKYMDMQVUYV4P30dX6Hyz85lP+g8lHf7bLu074bbX/tFoK2E4XHPkvAWNTnTMPCBusE1wyho86vYsanNliUMfJrE09SEoj1lOPYH0PUGTEvMCsNyIQmZ6I=
