language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.2.3.RELEASE/bin
- spring --version
script:
- ./build
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gturnquist@pivotal.io
  password:
    secure: NkMgsRbR+zA1t70bFcrjFoXLVToTS8Qi4KR1ogqTMao9eC/0hCj4yQro+VUPql1f+8QcAWgYFNqUjLijpacGAqwyHSovSy2Pk+VA31SmSR0vyKwu9VZZ5wRALqDpIpZdt2f/2eG4sZprbamjPeRNcOqzeRPt7nxbaLt9iAjouak=
  organization: spring.io
  space: Guides
  on:
    repo: gregturn/issue-aggregator
    branch: master
notifications:
  slack:
    secure: Z7xfbWEBn6vn+mplLM64G/YWK4+6wS4S98rMkib2XvA8GwTLX7IWvI6T66lpppvkYF3HaE7XXvA4Gj2EGGdG176K44Nh7UC2wuEv/8xl4o0mh8Ezs/cg2WzivNSL+y7kP49Jkt3/NL3y2nRwuprjqP0FxnaHCCTRUUCWfbUYsEc=
